spring:
  datasource:
    druid:
      driver-class-name:  com.mysql.jdbc.Driver
      url: jdbc:mysql://39.104.159.18:3306/springboot
      username: root
      password: root
  data:
    mongodb:
      uri: mongodb://39.104.159.18:27017
      database: test
