spring:
  datasource:
    druid:
      driver-class-name:  com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.104.159.18:3306/spring
      username: root
      password: root
  data:
    mongodb:
      uri: mongodb://39.104.159.18:27017
      database: test
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:/mapper/*.xml

